### ISSUE TITLE
Struggling to get ConfigurationCountries

### ISSUE THREAD

**Issue by tim-koehler** [cyruzin/golang-tmdb#25]
Hey @cyruzin,
I am having problems getting the ConfigurationCountries by calling GetConfigurationCountries. It seems like the return type is `*ConfigurationCountries` which is a pointer to a `[]struct`.
How can I iterate over that struct and extract the fields(`Iso3166_1` and `EnglishName`)? It is also likely that this is obvious and I am just a bit dumb right know 😅 

Would be great if you can give me an example.
Thanks 
Tim 😊

**Comment by tim-koehler** [comment]
Well...I figured it out myself.

```go
for _, country := range *rawCountryList {
    /*...*/
}
```

**Comment by cyruzin** [comment]
I was about to reply :) I am glad that you figured out.
