### ISSUE TITLE
Implement missing end-points.

### ISSUE THREAD

**Issue by cyruzin** [cyruzin/golang-tmdb#3]
Implement POST and DELETE end-points.

**Comment by vdepatla** [comment]
I can take this one

**Comment by cyruzin** [comment]
> I can take this one

@vdepatla nice :)

**Comment by vdepatla** [comment]
@cyruzin both POST and DELETE needs a session_id .. do we want to read it from env variable like api_key ?

**Comment by cyruzin** [comment]
I think that session_id comes from an authentication I'm right? Which endpoint you're implementing?

**Comment by vdepatla** [comment]
@cyruzin I am trying to implement this https://developers.themoviedb.org/3/movies/rate-movie

**Comment by vdepatla** [comment]
see this comment **A valid session or guest session ID is required. You can read more about how this works** https://developers.themoviedb.org/3/authentication/how-do-i-generate-a-session-id

**Comment by vdepatla** [comment]
@cyruzin I submitted a PR for the changes https://github.com/cyruzin/golang-tmdb/pull/8 however I see two tests are failing .. these tests are failing even with master when ran locally .. any idea ? below are the failing tests 
https://ci.appveyor.com/project/cyruzin/golang-tmdb/builds/28003032

**Comment by cyruzin** [comment]
@vdepatla I accepted your pull request :) I did some adjustments and added new tests.

**Comment by cyruzin** [comment]
Some endpoints still need to be implemented, so I'll leave this issue opened.
