### ISSUE TITLE
[feature] remove embedded structure

### ISSUE THREAD

**Issue by Eraac** [cyruzin/golang-tmdb#31]
**Is your feature request related to a problem? Please describe.**
Most (all?) results structure are embedded and not exportable, which made impossible to merge all results from many pages to one list

**Describe the solution you'd like**
Export 'results' structure

**Describe alternatives you've considered**
I've to create a list from the parent structure and do a double 'for' to iterate over all results

**Additional context**
For example https://github.com/cyruzin/golang-tmdb/blob/993aeec9e091f099e2455ee10b4dd2d5c7e02a84/movies.go#L800

**Comment by cyruzin** [comment]
Let me see if I got it right. Do you want a separate type just for the results?

**Comment by Eraac** [comment]
Yes absolutely, but also for other like genre https://github.com/cyruzin/golang-tmdb/blob/master/movies.go#L21

To give you concret example, instead of having a nice list of movies, my code look like this

```golang
func (p MovieAnnouncement) retrieveMoviesNowPlaying() ([]tmdb.MovieNowPlaying, error) {
	opts := map[string]string{"region": p.region, "language": p.language}

	movies := make([]tmdb.MovieNowPlaying, 0)

	for page, totalPages := 1, 1; page <= totalPages; page++ {
		opts["page"] = strconv.Itoa(page)
		ms, err := p.client.GetMovieNowPlaying(opts)
		if err != nil {
			return nil, fmt.Errorf("GetMovieNowPlaying (page: %d): %w", page, err)
		}
		totalPages = int(ms.TotalPages)

		movies = append(movies, *ms)
	}

	return movies, nil
}

func (p MovieAnnouncement) Run(ctx api.Context) error {
	results, err := p.retrieveMoviesNowPlaying(ctx)
	if err != nil {
		return err
	}

        // double for
	for i := range results {
		for _, movie := range results[i].Results {
		    // use movie
		}
	}
}
```

Instead of something like this
```golang
func (p MovieAnnouncement) retrieveMoviesNowPlaying() ([]tmdb.Movie, error) {
	opts := map[string]string{"region": p.region, "language": p.language}

	movies := make([]tmdb.Movie, 0)

	for page, totalPages := 1, 1; page <= totalPages; page++ {
		opts["page"] = strconv.Itoa(page)
		ms, err := p.client.GetMovieNowPlaying(opts)
		if err != nil {
			return nil, err
		}
		totalPages = int(ms.TotalPages)

		movies = append(movies, ms.Results...)
	}

	return movies, nil
}

func (p MovieAnnouncement) Run() error {
	movies, err := p.retrieveMoviesNowPlaying()
	if err != nil {
		return err
	}

	for _, movie := range movies {
	    // use movie
	}
}
```

Not really a big difference, but this make code more re-usable

**Comment by cyruzin** [comment]
@Eraac feel free to create a PR 😀 just keep the compatibility with v1.

**Comment by cyruzin** [comment]
@Eraac may you test this modifications?

**Comment by Eraac** [comment]
@cyruzin Yes perfect, I can now get rid of the double-loop

**Comment by cyruzin** [comment]
> @cyruzin Yes perfect, I can now get rid of the double-loop

Nice :D
