### ISSUE TITLE
function GetMovieChanges yield's weird string after marshal

### ISSUE THREAD

**Issue by shamith16** [cyruzin/golang-tmdb#39]
when GetMovieChanges or append_to_resonse used with changes as one of value the **changes** struct after marshal always has same weird string 
![image](https://user-images.githubusercontent.com/33453856/164879701-c84d26ca-6d24-4193-a741-88d74333b152.png)

On left I'm printing value before marshal and it's fine but after marshal result is weird string doesn't matter what movie I fetch

![image](https://user-images.githubusercontent.com/33453856/164880364-6c8a2798-f52a-4ed0-a1e3-78eb12844b7d.png)
Different movie same string after marshal

**Comment by shamith16** [comment]
Using jsoniter fixed it.

![image](https://user-images.githubusercontent.com/33453856/164882286-27f00da5-9d8e-48ca-9030-d33cc4b51d20.png)

**Comment by cyruzin** [comment]
If you want to extract the raw JSON data from the API, this wrapper is not the best option. You could access the API directly, using the GET method from HTTP Client.
