### ISSUE TITLE
Support for access token

### ISSUE THREAD

**Issue by sayem314** [cyruzin/golang-tmdb#44]
I would like to request adding support for TMDB API access token in the golang-tmdb library. Currently, the library only supports API key authentication.

https://developers.themoviedb.org/4/getting-started/authorization

**Comment by cyruzin** [comment]
Hi @sayem314, this wrapper only supports version 3 for now. Last time I checked, v4 was not complete, how is it now days?

**Comment by sayem314** [comment]
@cyruzin v4 is complete. You can check updated docs on tmdb docs.

**Comment by cyruzin** [comment]
@sayem314 I gave up on v2, so I added support in this PR: https://github.com/cyruzin/golang-tmdb/pull/57
