### ISSUE TITLE
Ability to modify http.Client or at least http.Client.Transport

### ISSUE THREAD

**Issue by rkollar** [cyruzin/golang-tmdb#5]
Hello,
it would be very useful if you can modify the http.Client inside the Client struct.
For example for replacing http.Client.Transport to get your own response caching or rate limiting. Or changing timeouts.
I did not submit a PR because there are multiple ways to do it (exporting Client.http, adding a parameter to Init(), adding a new method(s) to Client...). But the change should be trivial.

Thank you.

**Comment by cyruzin** [comment]
Hi @rkollar, thanks for the suggestion. I'll look into it today.

**Comment by cyruzin** [comment]
@rkollar issue resolved with this commit https://github.com/cyruzin/golang-tmdb/commit/000fba67c385e489aff311e7107f5d3afee3c563
