### ISSUE TITLE
[FEATURE]  Provides a method to replace baseURL for external unit testing

### ISSUE THREAD

**Issue by MangataL** [cyruzin/golang-tmdb#65]
**Is your feature request related to a problem? Please describe.**
other packages using the client cannot write a unit test because the baseURL variable cannot be modified and can only access the real tmdb address.

**Describe the solution you'd like**
add a method to modify baseURL

**Describe alternatives you've considered**

**Additional context**

**Comment by cyruzin** [comment]
@MangataL https://github.com/cyruzin/golang-tmdb/releases/tag/v1.6.4
