### ISSUE TITLE
[FEATURE] - Implement post, put, post methods for lists

### ISSUE THREAD

**Issue by cyruzin** [cyruzin/golang-tmdb#7]
Currently, only get method is working well.

**Comment by vdepatla** [comment]
I can take this one ..

**Comment by XdaemonX** [comment]
hello, i would like to take this one

**Comment by cyruzin** [comment]
> hello, i would like to take this one

Hi, take a look on this implementation: https://github.com/zmb3/spotify/blob/master/spotify.go#L166

What do you think? One generic function that handles these three http methods.

**Comment by XdaemonX** [comment]
Yeah, that would be much better, but do you mean it like implementation on project level so everything can call that function or just for the lists

**Comment by cyruzin** [comment]
> Yeah, that would be much better, but do you mean it like implementation on project level so everything can call that function or just for the lists

I mentioned the lists because they use all methods, but it would be for all functions.

**Comment by cyruzin** [comment]
Implemented: https://github.com/cyruzin/golang-tmdb/commit/34513504211d379ecb58c9aeb5baf3f9b4dbe496
